### ISSUE TITLE
Latin Modern, readability issues

### ISSUE THREAD

**Issue by wdolek** [vincentdoerig/latex-css#34]
I've added latex.css to my page and without any other styling, it is quite difficult to read the text - see screenshot below. I tried three displays (2 external, 1 notebook with native resolution), Firefox and Chrome (Windows) - same result. Types are too thin, somehow blurry and too close to each other - however it doesn't seem like kerning was somehow overdone; of course, increasing `font-size` helped - but then font is too big obviously.

I'm aware that you are not author of LM font itself - is there any other variant of LM font, or is there any other but similar font? (Or perhaps, could be issue on my device?)

---

![image](https://user-images.githubusercontent.com/352808/101095674-941e3c80-35be-11eb-9294-ecba3cff1f8f.png)

**Comment by vincentdoerig** [comment]
Hey, thanks for opening this issue. Latin Modern is indeed a very thin typeface. Since it was originally made for print, it is not optimised for the computer screen. I imagine this is why it sometimes looks a bit funky. The only thing I can think of to "fix" this, is that you could try increasing the font weight. But I'm not sure whether this really makes it better...

The source for LM can be found [here](http://www.gust.org.pl/projects/e-foundry/latin-modern/index_html), maybe someone could make a wider version of it?

I'm thinking about adding a second typeface to the project but I don't know which one and I'm not aware of similar fonts.

**Comment by tiagofilipesilva** [comment]
When I started using LaTeX to typeset documents in the computer I also used Latin Modern as the default.

At a certain point the screen and print technologies were much better and I switched to [Libertinus](https://github.com/alerque/libertinus) because Latin Modern was too thin and it lacked some features that Linux Libertine and Libertinus had.

**Comment by vincentdoerig** [comment]
Thanks for sharing this @tiagofilipesilva! This seems like a great alternative to LM. I'll make a PR in the following days adding the typeface to the project.
