### ISSUE TITLE
Multiline table headers borders drawn at every line of the header rows

### ISSUE THREAD

**Issue by barslmn** [vincentdoerig/latex-css#58]
Hi,
Thanks for the nice style.

I think it should just draw the border at the end of the table header instead of the every line.
I think these lines draw the border in the table header: 
https://github.com/vincentdoerig/latex-css/blob/34d7276af6d33cde2ad787216518537ae5daa333/style.css#L312-L314

tbody already has a top border so I think these can be omitted. Or maybe just  made the border be drawn on the last header line.

![image](https://github.com/vincentdoerig/latex-css/assets/43095157/22698305-0ec0-4ab5-b32d-2abaff81d99c)

Best, B

**Comment by vihuna** [comment]
Hi @barslmn, another LaTeX.css user here.

> I think it should just draw the border at the end of the table header instead of the every line

This is probably intended by design, as you can see in **Table 2** from [documentation](https://latex.vercel.app/#tables). LaTeX.css default style for tables is inspired by LaTeX `booktabs` package guidelines.

Since LaTeX.css version [v1.10.0](https://github.com/vincentdoerig/latex-css/releases/tag/v1.10.0), some custom table borders are allowed (see [release notes](https://github.com/vincentdoerig/latex-css/releases/tag/v1.10.0) and [documentation](https://latex.vercel.app/#table-borders)), so you can begin with a borderless table and add the borders you want.

Regards.

**Comment by barslmn** [comment]
Thanks for letting me know about the update @vihuna . 
Looking back at that table, I just made it a single line header.
![image](https://github.com/vincentdoerig/latex-css/assets/43095157/613b402d-b6b1-4cfa-ae6a-1adfcd8376c9)
